name: Deploy to droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        # run the tests using the run_tests.yml file
        npm test -- --config run_tests.yml

    - name: SSH into droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /github/My_Project
          git pull origin main
          command: 'python main.py'

            
