name: CD pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          sudo apt-get install python3-venv -y
          python3 -m venv venv
          source venv/bin/activate
          pip3 install -r requirements.txt
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            cd /var/www/My-Project
            git pull origin main
            source venv/bin/activate
            flask db upgrade
            sudo systemctl restart myapp.service
            sudo service nginx restart

      
            
            
