name: Deploy to droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: |
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: python -m pytest

    - name: SSH into droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /github/My_Project
          git pull origin main
          gunicorn main:app -b 0.0.0.0:8080


            
