name: My Pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SSH agent and add private key
        run: |
          function start_agent {
              eval "$(ssh-agent -s)"
              ssh-add ~/.ssh/droplet
          }
          if [[ ! $(pgrep ssh-agent) ]]; then
              start_agent
          fi

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            cd /var/www/My_Project
            git pull origin main

      
            
            
