name: Deploy to Ubuntu Server
on:
  push:
    branches: [main]

env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: ${{ secrets.SSH_PORT }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SSH agent and add key
        run: |
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/droplet
          chmod 600 ~/.ssh/droplet
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/droplet

      - name: Git pull from remote server
        run: ssh ${SSH_USERNAME}@${SSH_HOST} -p ${SSH_PORT} 'cd /var/www/My_Project && git pull'

            
            
