name: Deploy to droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /tmp
          ls -a
        host: ${{ secrets.SSH_HOST }}
        user: root
        key: ${{ secrets.SSH_PRIVATE_KEY}}
            script:|
              cd /var/www/My_Project
              git pull origin main

            
