name: Deploy to droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH into droplet
      uses: appleboy/ssh-action@master
      with:
        script_stop: true
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          whoami
          cd /var/www/My_Project
          git pull origin main

            
