name: Print Changes
on: [push]
jobs:
  print_changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Print Changes
      run: git log --pretty=format:"%h - %an, %ar : %s"
